import type { Metadata } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import  Header from "@/components/Header";
import {Footer} from "@/components/Footer";
import { Banner } from "@/components/Banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Orion",
  description: "Generated by create next app",
  icons:{
    
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={clsx(inter.className, "antialiased")}>
      <Banner />
      <Header />
            <main>{children}</main>
          <Footer />
      </body>
    
    </html>
  );
}
